[build]
publish = "docs/dist/spa"
command = "pnpm run build"

[build.environment]
NODE_OPTIONS = "--max_old_space_size=4096"
NODE_VERSION = "20"
PNPM_FLAGS = "--shamefully-hoist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
