// IMPORTANT NOTE
// We need to import this file both in app and quasar.conf.js.
// Since quasar.conf.js runs on Node context and this file can't be transpiled before build, we need to make Node happy, and can't use ES modules and such.

const iconSets = [
  {
    label: '@quasar/extras',
    children: [
      {
        label: 'Material Icons (Google)',
        value: 'material-icons',
        packageName: '@quasar/extras',
        icons: true,
      },
      {
        label: 'Material Icons Outlined (Google)',
        value: 'material-icons-outlined',
        packageName: '@quasar/extras',
        icons: true,
      },
      {
        label: 'Material Icons Round (Google)',
        value: 'material-icons-round',
        packageName: '@quasar/extras',
        icons: true,
      },
      {
        label: 'Material Icons Sharp (Google)',
        value: 'material-icons-sharp',
        packageName: '@quasar/extras',
        icons: true,
      },
      {
        label: 'Material Symbols Outlined (Google)',
        value: 'material-symbols-outlined',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Material Symbols Rounded (Google)',
        value: 'material-symbols-rounded',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Material Symbols Sharp (Google)',
        value: 'material-symbols-sharp',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'MDI v7 (Material Design Icons)',
        value: 'mdi-v7',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.15',
      },
      {
        label: 'MDI v6 (Material Design Icons)',
        value: 'mdi-v6',
        packageName: '@quasar/extras',
        icons: true,
      },
      { label: 'MDI v5 (Material Design Icons)', value: 'mdi-v5', packageName: '@quasar/extras' },
      {
        label: 'Fontawesome v6',
        value: 'fontawesome-v6',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.13',
      },
      {
        label: 'Fontawesome v5',
        value: 'fontawesome-v5',
        packageName: '@quasar/extras',
        icons: true,
      },
      {
        label: 'Ionicons v7',
        value: 'ionicons-v7',
        packageName: '@quasar/extras',
        icons: true,
        status: 'v1.16',
      },
      { label: 'Ionicons v6', value: 'ionicons-v6', packageName: '@quasar/extras', icons: true },
      { label: 'Ionicons v5', value: 'ionicons-v5', packageName: '@quasar/extras' },
      { label: 'Eva Icons', value: 'eva-icons', packageName: '@quasar/extras', icons: true },
      { label: 'Themify', value: 'themify', packageName: '@quasar/extras', icons: true },
      { label: 'Line Awesome', value: 'line-awesome', packageName: '@quasar/extras', icons: true },
      {
        label: 'Bootstrap Icons',
        value: 'bootstrap-icons',
        packageName: '@quasar/extras',
        icons: true,
      },
    ],
  },
  {
    label: 'quasar-extras-svg-icons',
    children: [
      {
        label: 'Akar Icons',
        value: 'akar-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.6',
      },
      {
        label: 'Ant Design Icons',
        value: 'ant-design-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.4',
      },
      {
        label: 'Box Icons',
        value: 'box-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Brand Icons',
        value: 'brand-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Brandico Icons',
        value: 'brandico-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Bytesize Icons',
        value: 'bytesize-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.10',
      },
      {
        label: 'Carbon Icons v11',
        value: 'carbon-icons-v11',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.18',
      },
      {
        label: 'Carbon Icons',
        value: 'carbon-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.7',
      },
      {
        label: 'Carbon Pictograms v12',
        value: 'carbon-pictograms-v12',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.18',
      },
      {
        label: 'Carbon Pictograms',
        value: 'carbon-pictograms',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.7',
      },
      {
        label: 'Clarity Icons v6',
        value: 'clarity-icons-v6',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.20',
      },
      {
        label: 'Clarity Icons',
        value: 'clarity-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12.1',
      },
      {
        label: 'Codicons',
        value: 'codicons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.4',
      },
      {
        label: 'Cool Icons',
        value: 'cool-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.3',
      },
      {
        label: 'CoreUI Icons v3',
        value: 'coreui-icons-v3',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.28',
      },
      {
        label: 'CoreUI Icons',
        value: 'coreui-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Country Flag Icons',
        value: 'country-flag-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.6',
      },
      {
        label: 'Dashicons',
        value: 'dashicons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.19',
      },
      {
        label: 'Dev Icons',
        value: 'dev-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Drip Icons',
        value: 'drip-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.10',
      },
      {
        label: 'Elusive FontIcon',
        value: 'elusive-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Entypo+ Icons',
        value: 'entypo-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.4',
      },
      {
        label: 'Evil Icons',
        value: 'evil-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.9',
      },
      {
        label: 'Feather Icons',
        value: 'feather-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.9',
      },
      {
        label: 'Flat Color Icons',
        value: 'flat-color-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'FlatUI Icons',
        value: 'flatui-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Fluent Icons',
        value: 'fluentui-system-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Fontisto Icons',
        value: 'fontisto-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12',
      },
      {
        label: 'Foundation Icons',
        value: 'foundation-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Geom Icons',
        value: 'geom-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'GitLab Icons v3',
        value: 'gitlab-icons-v3',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.23',
      },
      {
        label: 'GitLab Icons',
        value: 'gitlab-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.16',
      },
      {
        label: 'Glyphs Brands',
        value: 'glyphs-brands',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12.1',
      },
      {
        label: 'Glyphs Core Icons',
        value: 'glyphs-core-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12',
      },
      {
        label: 'Grid Icons',
        value: 'grid-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.6',
      },
      {
        label: 'Health Icons v2',
        value: 'health-icons-v2',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Health Icons',
        value: 'health-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.7',
      },
      {
        label: 'Hero Icons v2',
        value: 'hero-icons-v2',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.24',
      },
      {
        label: 'Hero Icons',
        value: 'hero-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Icomoon Free Icons',
        value: 'icomoon-free-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.3',
      },
      {
        label: 'Iconoir Icons v7',
        value: 'iconoir-icons-v7',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.34',
      },
      {
        label: 'Iconoir Icons v6',
        value: 'iconoir-icons-v6',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.27',
      },
      {
        label: 'Iconoir Icons v5',
        value: 'iconoir-icons-v5',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.21',
      },
      {
        label: 'IconPark Icons',
        value: 'iconpark-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12',
      },
      {
        label: 'Icons Material (mui)',
        value: 'icons-material',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.17',
      },
      {
        label: 'Ikonate',
        value: 'ikonate',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Ikons',
        value: 'ikons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.10',
      },
      {
        label: 'Jam Icons',
        value: 'jam-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Keyrune Icons',
        value: 'keyrune-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.16',
      },
      {
        label: 'Linear Icons',
        value: 'linear-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Linecons',
        value: 'linecons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Maki Icons v8',
        value: 'maki-icons-v8',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.22',
      },
      {
        label: 'Maki Icons',
        value: 'maki-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Map Icons',
        value: 'map-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Material Icon Theme v5',
        value: 'material-icon-theme-v5',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Material Line Icons',
        value: 'material-line-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Material Theme Icons v3',
        value: 'material-theme-icons-v3',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.32',
      },
      {
        label: 'Material Theme Icons',
        value: 'material-theme-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Modern Icons',
        value: 'modern-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Octicons (Primer) v19',
        value: 'oct-icons-v19',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.30.6',
      },
      {
        label: 'Octicons (Primer) v18',
        value: 'oct-icons-v18',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.29',
      },
      {
        label: 'Octicons (Primer) v17',
        value: 'oct-icons-v17',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.15',
      },
      {
        label: 'Open Iconic',
        value: 'open-iconic',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.9',
      },
      {
        label: 'Openmoji Icons v14',
        value: 'openmoji-icons-v14',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.22',
      },
      {
        label: 'Openmoji Icons',
        value: 'openmoji-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.13',
      },
      {
        label: 'Pixelart Icons',
        value: 'pixelart-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Phosphor Icons v2',
        value: 'phosphor-icons-v2',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Phosphor Icons',
        value: 'phosphor-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.12',
      },
      {
        label: 'Polaris Icons v9',
        value: 'polaris-icons-v9',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.37',
      },
      {
        label: 'Prime Icons v6',
        value: 'prime-icons-v6',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.25',
      },
      {
        label: 'Prime Icons',
        value: 'prime-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Radix-UI Icons',
        value: 'radix-ui-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.5',
      },
      {
        label: 'Remix Icons v3',
        value: 'remix-icons-v3',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.30',
      },
      {
        label: 'Remix Icons',
        value: 'remix-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Simple Icons v13',
        value: 'simple-icons-v13',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Simple Icons v12',
        value: 'simple-icons-v12',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Simple Icons v11',
        value: 'simple-icons-v11',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v2.0',
      },
      {
        label: 'Simple Line Icons',
        value: 'simple-line-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.9',
      },
      {
        label: 'Stroke 7 Icons',
        value: 'stroke7-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.14',
      },
      {
        label: 'Subway Icons',
        value: 'subway-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'System UIcons',
        value: 'system-uicons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.5',
      },
      {
        label: 'Tabler Icons v2',
        value: 'tabler-icons-v2',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.28',
      },
      {
        label: 'Tabler Icons',
        value: 'tabler-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
      {
        label: 'Teeny Icons',
        value: 'teeny-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.2',
      },
      {
        label: 'UIW Icons',
        value: 'uiw-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.6',
      },
      {
        label: 'Unicons',
        value: 'unicons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.1',
      },
      {
        label: 'Vaadin Icons v24',
        value: 'vaadin-icons-v24',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.29',
      },
      {
        label: 'Vaadin Icons v23',
        value: 'vaadin-icons-v23',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.15',
      },
      {
        label: 'Vaadin Icons',
        value: 'vaadin-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.3',
      },
      {
        label: 'Weather Icons',
        value: 'weather-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.6',
      },
      {
        label: 'Webfont Medical Icons',
        value: 'webfont-medical-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.7',
      },
      {
        label: 'Windows Icons',
        value: 'windows-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
        status: 'v1.11',
      },
      {
        label: 'Zond Icons',
        value: 'zond-icons',
        packageName: 'quasar-extras-svg-icons',
        icons: true,
      },
    ],
  },
]

const flattenedIconSets = Object.values(iconSets).flatMap(({ children }) => children)

export { iconSets, flattenedIconSets }
